<?php return array(
    'root' => array(
        'name' => 'mediawiki/core',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '8841bc0bbe5692289892c976c970ea3f3af5138c',
        'type' => 'mediawiki-core',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'bacon/bacon-qr-code' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'reference' => '8674e51bb65af933a5ffaf1c308a660387c35c22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'benjaminhoegh/parsedown-extended' => array(
            'pretty_version' => 'v1.2.9',
            'version' => '1.2.9.0',
            'reference' => 'bfbbf48640504e272d1fe503536aa05e5a17026b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../benjaminhoegh/parsedown-extended',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.12.1',
            'version' => '0.12.1.0',
            'reference' => 'f510c0a40911935b77b86859eb5223d58d660df1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'christian-riesen/base32' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '2e82dab3baa008e24a505649b0d583c31d31e894',
            'type' => 'library',
            'install_path' => __DIR__ . '/../christian-riesen/base32',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.3.1',
            'version' => '3.3.1.0',
            'reference' => '63aaeac21d7e775ff9bc9d45021e1745c97521c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => '35e8d0af4486141bc745f23a29cc2091eb624a32',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.8',
            'version' => '1.5.8.0',
            'reference' => '560bdcf8deb88ae5d611c80a2de8ea9d0358cc0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'reference' => '6c1925561632e83d60a44492e0b344cf48ab85ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'cssjanus/cssjanus' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'befd1eb7b1e70ee2cd71cd5b9a86ff250d2e8423',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cssjanus/cssjanus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '8dfd07c6d2cf31c8da90c53b83c026c7696dda90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/common' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '9f5e6216ec66ac8f2281351b110bad0eded43e65',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/data-values' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '1084142918095dfedf9b6cc0de0755f8c4628264',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/data-values',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/interfaces' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '244d078954bc05edf8f8c6b088e848289171c3a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/interfaces',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/validators' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '83dbac2c5e9442e8fa2119c8b941ecb88156abe8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/validators',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '4be43904336affa5c2f70744a348312336afd0da',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1ca8f21980e770095a31456042471a57bc4c68fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '3.7.2',
            'version' => '3.7.2.0',
            'reference' => '0ac3c270590e54910715e9a1a044cc368df282b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'dfbaa3c2d2e9a9df1118213f3b8b0c597bb99fab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'b680156fa328f1dfd874fd48c7026c41570b9c6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'c6222283fa3f4ac679f8b9ced9a4e23f163e80d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/sql-formatter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '25a06c7bf4c6b8218f47928654252863ffc890a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/sql-formatter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '4.5.2',
            'version' => '4.5.2.0',
            'reference' => 'aec7fb1f008ed515f0580d7871dffa19428efb82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => '1.7.4',
            'version' => '1.7.4.0',
            'reference' => 'cb17b6477dfff935958ba01325f2e8a2bfa6dab3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'erusev/parsedown-extra' => array(
            'pretty_version' => '0.8.1',
            'version' => '0.8.1.0',
            'reference' => '91ac3ff98f0cea243bdccc688df43810f044dcef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown-extra',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'eventsauce/eventsauce' => array(
            'pretty_version' => '0.8.2',
            'version' => '0.8.2.0',
            'reference' => '3c413662af7e37c7a2ca4fd2b1cfe9365a7b6dae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../eventsauce/eventsauce',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezimuel/guzzlestreams' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'b4b5a025dfee70d6cd34c780e07330eb93d5b997',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/guzzlestreams',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezimuel/ringphp' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '7887fc8488013065f72f977dcb281994f5fde9f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/ringphp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.17.0',
            'version' => '4.17.0.0',
            'reference' => 'bbc513d79acf6691fa9cf10f192c90dd2957f18c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'felixfbecker/advanced-json-rpc' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'reference' => 'b5f37dbff9a8ad360ca341f3240dc1c168b45447',
            'type' => 'library',
            'install_path' => __DIR__ . '/../felixfbecker/advanced-json-rpc',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'giorgiosironi/eris' => array(
            'pretty_version' => '0.14.0',
            'version' => '0.14.0.0',
            'reference' => '3e43f40ee4e82fef5b6ce6da02cc8534817b1ff9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giorgiosironi/eris',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'grogy/php-parallel-lint' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.7.1',
            'version' => '7.7.1.0',
            'reference' => '085b026db54d4b5012f727c80c9958e8b8cbc454',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '6ea8dd08867a2a42619d65c3deb2c0fcbf81c8f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'a70f5c95fb43bc83f07c9c948baa0dc1829bf201',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.2',
            ),
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '8c3d0a3f6af734494ad8f6fbbee0ba92422859f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'jakobo/hotp-php' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'ff2f13d1918001e54b3f49deb1d366bcfcc98437',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakobo/hotp-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-color' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jakub-onderka/php-console-highlighter' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jakub-onderka/php-parallel-lint' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jeroen/file-fetcher' => array(
            'pretty_version' => '6.1.0',
            'version' => '6.1.0.0',
            'reference' => 'd38fb0587b52b28bd24fda599f2da69ac8530453',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/file-fetcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'johnkary/phpunit-speedtrap' => array(
            'pretty_version' => 'v4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'd6600d2218396b78856c335f83479503957a5fa9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../johnkary/phpunit-speedtrap',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => 'v5.2.13',
            'version' => '5.2.13.0',
            'reference' => 'fbbe7e5d79f618997bc3332a6f49246036c45793',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'liuggio/statsd-php-client' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'reference' => 'c42e6d6687b7b2d7683186ec7f4f03351cc3dbca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../liuggio/statsd-php-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'b8174494eda667f7d13876b4a7bfef0f62a7c0d1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mck89/peast' => array(
            'pretty_version' => 'v1.16.2',
            'version' => '1.16.2.0',
            'reference' => '2791b08ffcc1862fe18eef85675da3aa58c406fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mck89/peast',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '8841bc0bbe5692289892c976c970ea3f3af5138c',
            'type' => 'mediawiki-core',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/data-values' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/http-request' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '1818e0731561621121fcc9da90f244a727ef0989',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/http-request',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/mediawiki-codesniffer' => array(
            'pretty_version' => 'v43.0.0',
            'version' => '43.0.0.0',
            'reference' => 'c559bc02e87b0a969b6ed7380d7fa1d02738158b',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../mediawiki/mediawiki-codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'mediawiki/mediawiki-phan-config' => array(
            'pretty_version' => '0.14.0',
            'version' => '0.14.0.0',
            'reference' => '58c01ba9cea443c9d345dc1ba87ffe082a188633',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/mediawiki-phan-config',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'mediawiki/parser-hooks' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '45660efef737bcf33abbbb12c1ddb049c4e713fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/parser-hooks',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/phan-taint-check-plugin' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => '01fb7e924a2e9fa58e88eda61775feccee38aad6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/phan-taint-check-plugin',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'mediawiki/semantic-media-wiki' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '0a8af7546b81f6dcab3f336f14023c8e7aea3805',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticMediaWiki',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'microsoft/tolerant-php-parser' => array(
            'pretty_version' => 'v0.1.2',
            'version' => '0.1.2.0',
            'reference' => '3eccfd273323aaf69513e2f1c888393f5947804b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../microsoft/tolerant-php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.9.2',
            'version' => '2.9.2.0',
            'reference' => '437cb3628f4cf6042cc10ae97fc2b8472e48ca1f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-alertbanners' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => 'e72b1f6acea26659be41c9d74c0b43e0ec992b22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-alertbanners',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-commonuserinterface' => array(
            'pretty_version' => '5.0.1',
            'version' => '5.0.1.0',
            'reference' => 'acbe6395018fe548d4c05914060a733150dee42a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-commonuserinterface',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-commonwebapis' => array(
            'pretty_version' => '2.0.26',
            'version' => '2.0.26.0',
            'reference' => '5b4ba8c7313c2ddf93f36efdc96f73bc9aff66cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-commonwebapis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-contentprovisioner' => array(
            'pretty_version' => '2.1.4',
            'version' => '2.1.4.0',
            'reference' => '5190edd2058950b8b7da283695acec9d924f4f2e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-contentprovisioner',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-datastore' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => '47f914673c76381fb1470a99c732d18448d4fdf0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-datastore',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-dynamicconfig' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '53e25515ea89693822cf70212f9082f1f75aa27a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-dynamicconfig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-events' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => '33fd9de7dcd399dc80a3401765a680b8f4b988ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-events',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-formengine' => array(
            'pretty_version' => '2.0.17',
            'version' => '2.0.17.0',
            'reference' => '993f0c650a77de9b51c4c9830e7c325bfc1e0b4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-formengine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-manifestregistry' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => '4f4b53bbc25e4108b75cc35f708ec432306816e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-manifestregistry',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-runjobstrigger' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '51dee04e8ddb0f8f17ac26396814ed78e4bdbabe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-runjobstrigger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-utils' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'c8909f8143c3771b2e83f45c676b8bc3bf1883a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-component-wikitext' => array(
            'pretty_version' => '6.0.1',
            'version' => '6.0.1.0',
            'reference' => 'f9e7928e73d05e755fbe25855db090b4e575c0e1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-component-wikitext',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-componentloader' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'd4a0b61ac6bc97d367402d619762d3745b0eb3e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-componentloader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mwstake/mediawiki-lib-nodes' => array(
            'pretty_version' => '1.0.10',
            'version' => '1.0.10.0',
            'reference' => 'dc787aaf48969b89274849b39dfec2466a21de11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mwstake/mediawiki-lib-nodes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '3a6b9a42cd8f8771bd4295d13e1423fa7f3d942c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'netresearch/jsonmapper' => array(
            'pretty_version' => 'v4.5.0',
            'version' => '4.5.0.0',
            'reference' => '8e76efb98ee8b6afc54687045e1b8dba55ac76e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../netresearch/jsonmapper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nichework/tag-builder' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '5f3a2d0b2058ca64feff639030843ed08b80d0b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nichework/tag-builder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.19.1',
            'version' => '4.19.1.0',
            'reference' => '4e1b88d21c69391150ace211e9eaf05810858d0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'onoi/blob-store' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'c3e1f15214977e904fc0e91e0480175a464977ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/blob-store',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/cache' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'ecc999186aab7c8db411aedd892b2e5fe5a0b422',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/callback-container' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'cf2f4dda1b2479bc786985fdb5554af528d03e52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/callback-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/event-dispatcher' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2af64e3997fc59b6d1e1f8f77e65fd6311c37109',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/http-request' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'onoi/message-reporter' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'reference' => 'ead8ef8f2868ccee6881e471295ebbaf8428c96c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/message-reporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/remi' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'reference' => '48898ecd1387656f6decc5bb1e38b4ecbdde5e4a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/remi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'oojs/oojs-ui' => array(
            'pretty_version' => 'v0.49.1',
            'version' => '0.49.1.0',
            'reference' => 'e217752a0dfaf6f494b29d2eb46237dc08ff24ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oojs/oojs-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'opensearch-project/opensearch-php' => array(
            'pretty_version' => '2.3.1',
            'version' => '2.3.1.0',
            'reference' => '1866e6ee95c15036038d6c95a5c54c6fe648de36',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opensearch-project/opensearch-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'param-processor/param-processor' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '0850dc2af72d31b8f645e0f87a44ff4b68583a64',
            'type' => 'library',
            'install_path' => __DIR__ . '/../param-processor/param-processor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'reference' => '4fda3292ac6bf226d8841cfd8ee3cf4e28395c01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.12',
            'version' => '1.10.12.0',
            'reference' => 'd032c7c9335e96d5954ac6e93d33955f3b7246e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.11.1',
            'version' => '1.11.1.0',
            'reference' => '0ae529d6f8358e29a7eaa8b314e5bcf168bfcec8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.15',
            'version' => '1.10.15.0',
            'reference' => 'ce0adade8b97561656ace07cdaac4751c271ea8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phan/phan' => array(
            'pretty_version' => '5.4.3',
            'version' => '5.4.3.0',
            'reference' => '86a7acd99c1239b8867b49feca2398851212e7fe',
            'type' => 'project',
            'install_path' => __DIR__ . '/../phan/phan',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-parallel-lint/php-console-color' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '7adfefd530aa2d7570ba87100a99e2483a543b88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-parallel-lint/php-console-color',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-parallel-lint/php-console-highlighter' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '5b4803384d3303cf8e84141039ef56c8a123138d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-parallel-lint/php-console-highlighter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-parallel-lint/php-parallel-lint' => array(
            'pretty_version' => 'v1.4.0',
            'version' => '1.4.0.0',
            'reference' => '6db563514f27e19595a19f45a4bf757b6401194e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-parallel-lint/php-parallel-lint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpcsstandards/phpcsextra' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '746c3190ba8eb2f212087c947ba75f4f5b9a58d5',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcsstandards/phpcsextra',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpcsstandards/phpcsutils' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'reference' => '908247bc65010c7b7541a9551e002db12e9dae70',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcsstandards/phpcsutils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.4.1',
            'version' => '5.4.1.0',
            'reference' => '9d07b3f7fdcf5efec5d1609cba3c19c5ea2bdc9c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'reference' => '153ae662783729388a584b4361f2545e4d841e3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.29.1',
            'version' => '1.29.1.0',
            'reference' => '59ee38f7480904cd6487e5cbdea4d80ff2758719',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.30.1',
            'version' => '1.30.1.0',
            'reference' => '51b95ec8670af41009e2b2b56873bad96682413e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.32',
            'version' => '9.2.32.0',
            'reference' => '85402a822d1ecf1db1096959413d35e1c37cf1a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.6.16',
            'version' => '9.6.16.0',
            'reference' => '3767b2c56ce02d01e3491046f33466a1ae60a37f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
                1 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.12.4',
            'version' => '0.12.4.0',
            'reference' => '2fd717afa05341b4f8152547f142cd2f130f6818',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.7.6',
            'version' => '4.7.6.0',
            'reference' => '91039bc1faa45ba123c4328958e620d382ec7088',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.11.0',
            'version' => '2.11.0.0',
            'reference' => '1a8460931ea36dc5c76838fec5734d55c88c6831',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.7.6',
            ),
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.15',
            ),
        ),
        'sabre/event' => array(
            'pretty_version' => '5.1.7',
            'version' => '5.1.7.0',
            'reference' => '86d57e305c272898ba3c28e9bd3d65d5464587c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/event',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '2b56bea83a09de3ac06bb18b92f068e60cc6f50b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'reference' => 'fa0f136dd2334583309d32b62544682ee972b51a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '25f207c40d62b8b7aa32f5ab026c53561964053a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => 'ba01945089c3a293b01ba9badc29ad55b106b0bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.5',
            'version' => '5.1.5.0',
            'reference' => '830c43a844f1f8d5b7a1f6d6076b784454d8b7ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => '78c00df8f170e02473b682df15bfcdacc3d32d72',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.7',
            'version' => '5.0.7.0',
            'reference' => 'bca7df1f32ee6fe93b4d4a9abbf69e13a4ada2c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'e1e4a170560925c26d424b6a03aed157e7dcc5c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => '05d5692a7993ecccd56a03e40cd7e5b09b1d404e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.10.1',
            'version' => '1.10.1.0',
            'reference' => '76d449a358ece77d6f1d6331c68453e657172202',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serialization/serialization' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '6fa293415e2b70c30c1e673d8bcd04d27dc15e44',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serialization/serialization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.8.1',
            'version' => '3.8.1.0',
            'reference' => '14f5fff1e64118595db5408e946f3a22c75807f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v7.1.4',
            'version' => '7.1.4.0',
            'reference' => '1eed7af6961d763e7832e874d7f9b21c3ea9c111',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.4.40',
            'version' => '5.4.40.0',
            'reference' => 'ea43887e9afd2029509662d4f95e8b5ef6fc9bbb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '0e0d29ce1f20deffb4ab1b016a7257c4f1e789a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.17.1',
            ),
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.17.1',
            ),
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '87b68208d5c1188808dd7839ee1e6c8ec3b02f1b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'c565ad1e63f30e7477fc40738343c62b40bc672d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php82' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '559d488c38784112c78b9bf17c5ce8366a265643',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php82',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '86fcae159633351e5fd145d1c47de6c528f8caff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'bd1d9e59a81d8fa4acdcea3f617c581f7475a80f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v7.1.4',
            'version' => '7.1.4.0',
            'reference' => '6cd670a6d968eaeb1c77c2e76091c45c56bc367b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.1.4',
            'version' => '7.1.4.0',
            'reference' => 'a5fa7481b199090964d6fd5dab6294d5a870c7aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.4.35',
            'version' => '5.4.35.0',
            'reference' => 'e78db7f5c70a21f0417a31f414c4a95fe76c07e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => '737eda637ed5e28c3413cb1ebe8bb52cbf1ca7a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tysonandre/var_representation_polyfill' => array(
            'pretty_version' => '0.1.3',
            'version' => '0.1.3.0',
            'reference' => 'e9116c2c352bb0835ca428b442dde7767c11ad32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tysonandre/var_representation_polyfill',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'wikimedia/alea' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'ef39b2c50af83c2b0c358bcb2ef8ce9d709bc054',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/alea',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'wikimedia/assert' => array(
            'pretty_version' => 'v0.5.1',
            'version' => '0.5.1.0',
            'reference' => '27c983fddac1197dc37f6a7cec00fc02861529cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/at-ease' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'e8ebaa7bb7c8a8395481a05f6dc4deaceab11c33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/at-ease',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/base-convert' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'aa997185e0b42c1f61a11f3e1980cad144175111',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/base-convert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/bcp-47-code' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '0d2204a8c3bb99be6253f9326df1c61093d2bb05',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/bcp-47-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cdb' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '3d7622f39319ea2149cac92415222d1fb39c46d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cdb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cldr-plural-rule-parser' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '83d78cb8018d5c0f66fd6d0efff6a8ae2de92d36',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cldr-plural-rule-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/common-passwords' => array(
            'pretty_version' => 'v0.5.0',
            'version' => '0.5.0.0',
            'reference' => 'ff3920985ef3c2e23d3b262e0620ff3f83292ac3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/common-passwords',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'a03d426c8e9fb2c9c569d9deeb31a083292788bc',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/css-sanitizer' => array(
            'pretty_version' => 'v5.3.0',
            'version' => '5.3.0.0',
            'reference' => 'dbe2db3dadce07bd68bab27ca097e27808f3145a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/css-sanitizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/equivset' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => '2a8cae4bb2c1aa102eea9fcb6e4d4de1d46e59f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/equivset',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/html-formatter' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => 'c2fdae55da33feb6d44d34ddc66c4b007981bcf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/html-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/idle-dom' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '631555d5868bf29427cb015906e666faf09abeea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/idle-dom',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-utils' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '119e0ed321e967b4f5748a404fa8a3eb5dad4aa3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/json-codec' => array(
            'pretty_version' => 'v2.2.1',
            'version' => '2.2.1.0',
            'reference' => '6ed58a76c495e23f4bd82a15e1222b2f4db004a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/json-codec',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/langconv' => array(
            'pretty_version' => '0.4.2',
            'version' => '0.4.2.0',
            'reference' => '4bd255fd316df6650c489fa0f9b621c48458859b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/langconv',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v4.2.1',
            'version' => '4.2.1.0',
            'reference' => '9bdb3fda0452a05769e51d9941f2cfc0871d5fc0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/minify' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'cfe7568b1b005d37cff5897f40dbcd96cf18a969',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/normalized-exception' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'ed9fc13d75f65c80dc1a95d4792658c97fd782e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/normalized-exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/object-factory' => array(
            'pretty_version' => 'v5.0.1',
            'version' => '5.0.1.0',
            'reference' => 'a0439aac5f14e218dc1f40a98eb14e4b26a01341',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/object-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/parsoid' => array(
            'pretty_version' => 'v0.19.0',
            'version' => '0.19.0.0',
            'reference' => 'c0657fb6c219ab336fdd95bc7876f697cbb34492',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/parsoid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/php-session-serializer' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '40c9761329415ada958688d43ba4b8a447aa3037',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/php-session-serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/purtle' => array(
            'pretty_version' => 'v1.0.8',
            'version' => '1.0.8.0',
            'reference' => '8f106f38ff811906853511a934d7f5e86dce3d20',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/purtle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/relpath' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'b4dc7c1e8b4f7dd81c38c2071a2d5c2ace39fc8e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/relpath',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/remex-html' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => 'e39f23cf5074dee550bf059be38a9582b8998190',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/remex-html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/request-timeout' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'e306a7cb1fb3a1ca3ce93992c56efb62b537c4bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/request-timeout',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/running-stat' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => '0aa66cf58f98ca2de9972a8177cbec625c4c9969',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/running-stat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/scoped-callback' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'dd522a6cfb4c0180b0a39d12fc57046a347c4d81',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/scoped-callback',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/services' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'c63d949c363378a5f435cfd7a81932aa6f712462',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/shellbox' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => 'a3789ef67a3d07ee1dafed0b2001b6331e5ee5e0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/shellbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/testing-access-wrapper' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '975e89994a667b2ab10b36f99d049318b6137db8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/testing-access-wrapper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'wikimedia/textcat' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'dfdfb1c41bb016814a9d4da3aa68b62437b54a82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/textcat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/timestamp' => array(
            'pretty_version' => 'v4.1.1',
            'version' => '4.1.1.0',
            'reference' => '138f3099b46e3f6679ac100e5ab1932e89746a05',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/timestamp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/utfnormal' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '6f3690d3ca446d9745fa3410bb993470afd7bc25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/utfnormal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wait-condition-loop' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '9bb0894e8c5195d43b2f2babbe4cc8f36bd5be0e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wait-condition-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wikipeg' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'd9cdf02401e0625b1561efd495bc8292827f08c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wikipeg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wrappedstring' => array(
            'pretty_version' => 'v4.0.1',
            'version' => '4.0.1.0',
            'reference' => '0d526868d92fa855c70a845336a777c63b30b400',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wrappedstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/xmp-reader' => array(
            'pretty_version' => '0.9.1',
            'version' => '0.9.1.0',
            'reference' => '8338d6796984d747559dd3c8b5272608d8a665d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/xmp-reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/zest-css' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'e61a0fc4b9704b9c6b89d99b896ef8011deefc94',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/zest-css',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wmde/hamcrest-html-matchers' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'f0f727f80bdb97831628329cfe508fce2a44028a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wmde/hamcrest-html-matchers',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'zordius/lightncandy' => array(
            'pretty_version' => 'v1.2.6',
            'version' => '1.2.6.0',
            'reference' => 'b451f73e8b5c73e62e365997ba3c993a0376b72a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zordius/lightncandy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
